name: CI
on: pull_request
jobs:
  lint-and-test-package:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'
      - name: Generate test data
        run: | 
          cd TestDataGenerator
          python3 main.py
      - name: Build
        run:
          swift build
      - name: Run tests
        run: 
          swift test
