name: CI
on: pull_request
jobs:
  lint-and-test-package:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Generate test data
        run: | 
          cd TestDataGenerator
          python3 main.py
      - name: Build
        run: | 
          cd PeakSwift
          swift build
      - name: Run tests
        run: | 
          cd PeakSwift
          swift test
