name: CI
on: pull_request
jobs:
  lint-and-test-package:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: swiftlint
      - name: Build
        run: swift build
      - name: Run tests
        run: swift test
